# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predhelios.protoc

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='predhelios.protoc',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11predhelios.protoc\"(\n\nPredObject\x12\x0b\n\x03\x63oo\x18\x01 \x03(\x02\x12\r\n\x05score\x18\x02 \x01(\x02\"\xdd\x02\n\x05\x46rame\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x0e\n\x06n_objs\x18\x02 \x01(\x03\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\x03\x12\x1f\n\npedestrian\x18\x04 \x03(\x0b\x32\x0b.PredObject\x12\x1b\n\x06people\x18\x05 \x03(\x0b\x32\x0b.PredObject\x12\x1c\n\x07\x62icycle\x18\x06 \x03(\x0b\x32\x0b.PredObject\x12\x18\n\x03\x63\x61r\x18\x07 \x03(\x0b\x32\x0b.PredObject\x12\x18\n\x03van\x18\x08 \x03(\x0b\x32\x0b.PredObject\x12\x1a\n\x05truck\x18\t \x03(\x0b\x32\x0b.PredObject\x12\x1d\n\x08tricycle\x18\n \x03(\x0b\x32\x0b.PredObject\x12#\n\x0e\x61wningtricycle\x18\x0b \x03(\x0b\x32\x0b.PredObject\x12\x18\n\x03\x62us\x18\x0c \x03(\x0b\x32\x0b.PredObject\x12\x1a\n\x05motor\x18\r \x03(\x0b\x32\x0b.PredObject\".\n\x04\x44\x61ta\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x14\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x06.Frameb\x06proto3'
)




_PREDOBJECT = _descriptor.Descriptor(
  name='PredObject',
  full_name='PredObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coo', full_name='PredObject.coo', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='PredObject.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=61,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='Frame.time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_objs', full_name='Frame.n_objs', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='Frame.frame_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pedestrian', full_name='Frame.pedestrian', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='people', full_name='Frame.people', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bicycle', full_name='Frame.bicycle', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='car', full_name='Frame.car', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='van', full_name='Frame.van', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='truck', full_name='Frame.truck', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tricycle', full_name='Frame.tricycle', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='awningtricycle', full_name='Frame.awningtricycle', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bus', full_name='Frame.bus', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motor', full_name='Frame.motor', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=413,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='Data.location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='Data.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=461,
)

_FRAME.fields_by_name['pedestrian'].message_type = _PREDOBJECT
_FRAME.fields_by_name['people'].message_type = _PREDOBJECT
_FRAME.fields_by_name['bicycle'].message_type = _PREDOBJECT
_FRAME.fields_by_name['car'].message_type = _PREDOBJECT
_FRAME.fields_by_name['van'].message_type = _PREDOBJECT
_FRAME.fields_by_name['truck'].message_type = _PREDOBJECT
_FRAME.fields_by_name['tricycle'].message_type = _PREDOBJECT
_FRAME.fields_by_name['awningtricycle'].message_type = _PREDOBJECT
_FRAME.fields_by_name['bus'].message_type = _PREDOBJECT
_FRAME.fields_by_name['motor'].message_type = _PREDOBJECT
_DATA.fields_by_name['data'].message_type = _FRAME
DESCRIPTOR.message_types_by_name['PredObject'] = _PREDOBJECT
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
DESCRIPTOR.message_types_by_name['Data'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PredObject = _reflection.GeneratedProtocolMessageType('PredObject', (_message.Message,), {
  'DESCRIPTOR' : _PREDOBJECT,
  '__module__' : 'predhelios.protoc_pb2'
  # @@protoc_insertion_point(class_scope:PredObject)
  })
_sym_db.RegisterMessage(PredObject)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
  'DESCRIPTOR' : _FRAME,
  '__module__' : 'predhelios.protoc_pb2'
  # @@protoc_insertion_point(class_scope:Frame)
  })
_sym_db.RegisterMessage(Frame)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'predhelios.protoc_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  })
_sym_db.RegisterMessage(Data)


# @@protoc_insertion_point(module_scope)
